#!/bin/sh /etc/rc.common

START=91
USE_PROCD=1

start_service() {
  procd_open_instance
  procd_set_param command /usr/bin/hiddify-cli run -c /root/hiddify/configs.conf -d /root/hiddify/settings.conf
  procd_set_param stdout 1
  procd_set_param stderr 1
  procd_set_param respawn
  procd_close_instance
}
