#!/bin/sh /etc/rc.common

START=91
USE_PROCD=1

start_service() {
  procd_open_instance
  procd_set_param command /usr/bin/warp-plus --cfon --country GB --bind 0.0.0.0:9804 --test-url "https://1.1.1.1/cdn-cgi/trace/"
  procd_set_param stdout 1
  procd_set_param stderr 1
  procd_set_param respawn
  procd_close_instance
}
