#!/bin/sh /etc/rc.common

START=91
USE_PROCD=1

start_service() {
  procd_open_instance
  procd_set_param command /usr/bin/scanner -jobs 1000 -timeout 15 -urltest "https://cachefly.cachefly.net/1mb.test" -output "/root/ghost/configs.json"
  procd_set_param stdout 1
  procd_set_param stderr 1
  procd_close_instance
}
