#!/bin/sh

[ "$ACTION" = "ifup" ] && \
[ "$(uci get passwall2.@global[0].enabled)" = "1" ] && \
[ "$DEVICE" = "$(ip route | grep default | awk -F 'dev ' '{print $2}' | awk '{print $1}')" ] && \
/etc/init.d/warp-plus status | grep -q "running" && \
/etc/init.d/warp-plus restart
