name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - goos: linux
            goarch: amd64
          - goos: linux
            goarch: arm64
          - goos: linux
            goarch: arm
            goarm: 7
          - goos: linux
            goarch: riscv64
          - goos: linux
            goarch: mips64
            gomips: softfloat
          - goos: linux
            goarch: mips64le
            gomips: softfloat
          - goos: linux
            goarch: mips
            gomips: softfloat
          - goos: linux
            goarch: mipsle
            gomips: softfloat
          - goos: darwin
            goarch: arm64
          - goos: android
            goarch: arm64

    runs-on: ${{ matrix.goos == 'darwin' && 'macos-latest' || 'ubuntu-latest' }}

    env:
      GOOS: ${{ matrix.goos }}
      GOARCH: ${{ matrix.goarch }}
      GOARM: ${{ matrix.goarm }}
      GOMIPS: ${{ matrix.gomips }}
      CGO_ENABLED: 0
      GOTOOLCHAIN: go1.26.3
      ASSET_NAME: ${{ matrix.goos }}-${{ matrix.goarch }}${{ matrix.goarm && format('v{0}', matrix.goarm) || '' }}${{ matrix.gomips && format('-{0}', matrix.gomips) || '' }}

    steps:
      - name: Checkout codebase
        uses: actions/checkout@v5

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: "1.26.3"
          check-latest: true

      - name: Build Psiphon
        if: matrix.goos == 'linux'
        run: |
          git clone --depth 1 https://github.com/Psiphon-Labs/psiphon-tunnel-core.git
          pushd ./psiphon-tunnel-core || exit 1
          go build -o ../psiphon_${ASSET_NAME} -trimpath -ldflags "-s -w -buildid= -checklinkname=0 -X main.version=${{ github.ref }}" ./ConsoleClient
          popd

      - name: Upload Psiphon
        if: matrix.goos == 'linux'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: psiphon_${{ env.ASSET_NAME }}
          tag: ${{ github.ref }}
          overwrite: true

      - name: Build Scanner
        run: |
          go build -tags with_gvisor,with_quic,with_wireguard,with_utls,with_clash_api,with_conntrac -o scanner_${ASSET_NAME} .

      - name: Upload Scanner
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: scanner_${{ env.ASSET_NAME }}
          tag: ${{ github.ref }}
          overwrite: true
